### ISSUE TITLE
Creating new tournament or adding player should close Dialog.

### ISSUE THREAD

**Issue by lmx2k5** [MrHuds0n/golden#1]
When you create new tournament, after saving to filesystem, nothing happens. You should display maybe similar message as when " Add Player"  and close Dialog form. Same for Add player

**Comment by zanlib0** [comment]
Not closing the Add player dialog is fully intended behaviour, it allows for faster navigation using just the keyboard. I agree that the New tournament one should close after submitting, this will be fixed down the line. Thanks for reporting.
