### ISSUE TITLE
SoS calculation bug?

### ISSUE THREAD

**Issue by gereons** [MrHuds0n/golden#13]
I just ran a dummy tournament, where some SoS entries do not show the values I'm expecting.

<img width="926" alt="bildschirmfoto 2017-04-02 um 15 20 23" src="https://cloud.githubusercontent.com/assets/2861931/24587513/50dcc70c-17b8-11e7-8c5a-f563146b6753.png">
<img width="985" alt="bildschirmfoto 2017-04-02 um 15 20 32" src="https://cloud.githubusercontent.com/assets/2861931/24587514/54bb4678-17b8-11e7-83ca-318c227fb0eb.png">

Player F has played K and f. K has an average score of 1.5, f has 4. This should result in an SoS value of 2.75 (5.5 / 2.0), and thus in Player F being ranked first instead of second.

BTW, as eSoS is the second tiebreaker, I would suggest that it's also displayed in the rankings table.

**Comment by zanlib0** [comment]
Could you post the `cjson` file of the tournament here? This requires investigation.

**Comment by gereons** [comment]
Sure: [Test_Pairings-r2.cjson.zip](https://github.com/MrHuds0n/golden/files/888412/Test_Pairings-r2.cjson.zip)

**Comment by zanlib0** [comment]
The SOS is calculated correctly however it seems to be updated at odd times. This is fortunately much less of a severe issue than I first thought. A fix is coming shortly.

**Comment by zanlib0** [comment]
From now on the SOS is calculated before pairing up each round and upon refreshing the players view (just in case) rather than when scoring a match.
