### ISSUE TITLE
One player can play the same opponent multiple times.

### ISSUE THREAD

**Issue by zanlib0** [MrHuds0n/golden#16]
As per a pull request #15 by @gereons, the test shows the same player can be paired with one opponent more than once.

**Comment by gereons** [comment]
I do not think it is possible to solve the swiss pairing problem using a simple iterative algorithm, something more elaborate is needed. 

Alternatives to consider could the [Hungarian Algorithm](https://en.wikipedia.org/wiki/Hungarian_algorithm) as used by TOME, or a recursive backtracker as used by NRTM.

**Comment by zanlib0** [comment]
Yeah, I figured that one. I've tried figuring out how to do this though and I didn't come up with anything meaningful. I've talked with @hadrian88 about this and he suggested translating the implementation from ANRTournament to Golden. The problem with that is I cannot for the life of me locate anything specific in the ANRT files, I'm not too knowledgeable in C#.

**Comment by dodgepong** [comment]
Looks like that algorithm is here: https://github.com/morphinepl/ANRTournament/blob/master/ANRTournament/Objects/Tournament.cs#L475

**Comment by hadrian88** [comment]
Algorithm in ANRTournament is very well thought and works fine. I will translate it to Golden and commit changes when ready (in ~2 days from now)

**Comment by zanlib0** [comment]
I've rewritten the pairing algorithm based on @hadrian88's code, passed about 70K tests so I'll call it good.
