### ISSUE TITLE
Errors after saving tournament

### ISSUE THREAD

**Issue by lmx2k5** [MrHuds0n/golden#2]
Loaded tournament, add some rounds. Then save, in "Matches" view player names are lost.
![image](https://cloud.githubusercontent.com/assets/6040643/24493436/7bc9310e-1537-11e7-85a1-93d966ecb13a.png)
[log.txt](https://github.com/MrHuds0n/golden/files/881401/log.txt)
 Errors in console when try to "Score" (see log)

**Comment by zanlib0** [comment]
Could not reproduce, could you provide exact steps to where this occurs or provide a `.cjson` file prior to this error occuring?

**Comment by lmx2k5** [comment]
sample steps as following:
1. open app
2. click "Load Tournament", choose any, lets say "Sample tournament.cjson"
3. New Round, fill scores
4. Click "Save" and check "Matches" or "Rounds" will be empty names.

**Comment by zanlib0** [comment]
Acknowledged, seems like there's an issue with the serialisation functions. I will investigate into this further.

**Comment by zanlib0** [comment]
This solution is painfully inefficient but one that doesn't require rewriting a lot of code was needed. In case someone wants to suggest a better way to do it, I will just close this for the moment.
