### ISSUE TITLE
Creating Tournaments no longer seems to work

### ISSUE THREAD

**Issue by SpaceDivider** [MrHuds0n/golden#27]
I tried creating a new tournament, however no file is created. Adding players after creating a new tournament has no effect at all either.
I also tried creating a new tournament after loading the default tournament, but the data from the former tournament is still loaded and no new file is created.
There is no error message in the command line.

This issue was not present in version 1.1.2.

**Comment by zanlib0** [comment]
Oh, because during the creation of a new tournament the structure object is overwritten and was lacking certain properties which caused the serialisation to work on undefined. And there certainly were console errors.

#ItShouldWorkNow
