### ISSUE TITLE
Support for deleting/re-pairing rounds, and editing of previous scores.

### ISSUE THREAD

**Issue by gereons** [MrHuds0n/golden#9]
Communication errors and misclicks happen, and therefore it should be possible to delete the current round, correct score entries of the previous round and re-pair a new round.

**Comment by zanlib0** [comment]
This will be probably addressed at some point in the future, however as it stands the amount of work required to implement something like this makes it unlikely to be prioritised.

**Comment by zanlib0** [comment]
I implemented a save history which stores up to 30 last tournament structures with timestamps. I know this is perhaps not the most perfect way to do it, but it should allow for easy edits of incorrect scores provided the tournament organiser remembers to save their tournament, while not being labour-intensive.

If anyone has a better, future-proof solution to this, a PR is welcome.

Closing for now.
